minimum_pre_commit_version: "3.7.0"
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]

exclude: |
  (?x)^(
    projects/cifar-100-benchmark/artifacts/.*|
    projects/dataset-tool/backend/target/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.4.10
  #   hooks:
  #     - id: ruff
  #       args: ["--fix", "--exit-non-zero-on-fix"]
  #     - id: ruff-format
